-- MySQL Script generated by MySQL Workbench
-- dom 05 set 2021 02:40:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`real_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`real_state` ;

CREATE TABLE IF NOT EXISTS `mydb`.`real_state` (
  `idreal_state` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  `content` LONGTEXT NULL,
  `real_statecol` VARCHAR(255) NULL,
  `price` FLOAT(10,2) NULL,
  `bathrooms` INT NULL,
  `bedrooms` INT NULL,
  `property_area` INT NULL,
  `total_property_area` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`idreal_state`, `users_id`),
  INDEX `fk_real_state_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_real_state_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories_has_real_state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categories_has_real_state` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categories_has_real_state` (
  `categories_id` INT NOT NULL,
  `real_state_idreal_state` INT NOT NULL,
  PRIMARY KEY (`categories_id`, `real_state_idreal_state`),
  INDEX `fk_categories_has_real_state_real_state1_idx` (`real_state_idreal_state` ASC) VISIBLE,
  INDEX `fk_categories_has_real_state_categories_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_has_real_state_categories`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_real_state_real_state1`
    FOREIGN KEY (`real_state_idreal_state`)
    REFERENCES `mydb`.`real_state` (`idreal_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_profile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_profile` (
  `id` INT NOT NULL,
  `about` LONGTEXT NULL,
  `social_network` LONGTEXT NULL,
  `phone` VARCHAR(45) NULL,
  `mobile_phone` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_user_profile_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profile_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`real_state_photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`real_state_photos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`real_state_photos` (
  `id` INT NOT NULL,
  `photo` VARCHAR(255) NULL,
  `is_thumb` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `real_state_idreal_state` INT NOT NULL,
  `real_state_users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `real_state_idreal_state`, `real_state_users_id`),
  INDEX `fk_real_state_photos_real_state1_idx` (`real_state_idreal_state` ASC, `real_state_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_real_state_photos_real_state1`
    FOREIGN KEY (`real_state_idreal_state` , `real_state_users_id`)
    REFERENCES `mydb`.`real_state` (`idreal_state` , `users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
